// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/personal/task-management/internal/delivery/rest/middleware (interfaces: CasbinRBACService)
//
// Generated by this command:
//
//	mockgen -destination=./casbin_rbac_service.go -package=mocks github.com/personal/task-management/internal/delivery/rest/middleware CasbinRBACService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	uuid "github.com/google/uuid"
	user "github.com/personal/task-management/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockCasbinRBACService is a mock of CasbinRBACService interface.
type MockCasbinRBACService struct {
	ctrl     *gomock.Controller
	recorder *MockCasbinRBACServiceMockRecorder
	isgomock struct{}
}

// MockCasbinRBACServiceMockRecorder is the mock recorder for MockCasbinRBACService.
type MockCasbinRBACServiceMockRecorder struct {
	mock *MockCasbinRBACService
}

// NewMockCasbinRBACService creates a new mock instance.
func NewMockCasbinRBACService(ctrl *gomock.Controller) *MockCasbinRBACService {
	mock := &MockCasbinRBACService{ctrl: ctrl}
	mock.recorder = &MockCasbinRBACServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCasbinRBACService) EXPECT() *MockCasbinRBACServiceMockRecorder {
	return m.recorder
}

// ApplyResourceFilter mocks base method.
func (m *MockCasbinRBACService) ApplyResourceFilter(r *http.Request, role user.Role, userID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyResourceFilter", r, role, userID)
}

// ApplyResourceFilter indicates an expected call of ApplyResourceFilter.
func (mr *MockCasbinRBACServiceMockRecorder) ApplyResourceFilter(r, role, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyResourceFilter", reflect.TypeOf((*MockCasbinRBACService)(nil).ApplyResourceFilter), r, role, userID)
}

// HasPermission mocks base method.
func (m *MockCasbinRBACService) HasPermission(role user.Role, resource, action string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", role, resource, action)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockCasbinRBACServiceMockRecorder) HasPermission(role, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockCasbinRBACService)(nil).HasPermission), role, resource, action)
}
