// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/personal/task-management/internal/usecase (interfaces: TaskService)
//
// Generated by this command:
//
//	mockgen -destination=./task_service.go -package=mocks github.com/personal/task-management/internal/usecase TaskService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dtos "github.com/personal/task-management/internal/delivery/rest/dtos"
	task "github.com/personal/task-management/internal/domain/task"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
	isgomock struct{}
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskService) CreateTask(ctx context.Context, input dtos.CreateTaskInput) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, input)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceMockRecorder) CreateTask(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskService)(nil).CreateTask), ctx, input)
}

// DeleteTask mocks base method.
func (m *MockTaskService) DeleteTask(ctx context.Context, input dtos.DeleteTaskInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskServiceMockRecorder) DeleteTask(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskService)(nil).DeleteTask), ctx, input)
}

// GetEmployeeTasks mocks base method.
func (m *MockTaskService) GetEmployeeTasks(ctx context.Context, input dtos.GetEmployeeTasksInput) ([]*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeTasks", ctx, input)
	ret0, _ := ret[0].([]*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeTasks indicates an expected call of GetEmployeeTasks.
func (mr *MockTaskServiceMockRecorder) GetEmployeeTasks(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeTasks", reflect.TypeOf((*MockTaskService)(nil).GetEmployeeTasks), ctx, input)
}

// GetTask mocks base method.
func (m *MockTaskService) GetTask(ctx context.Context, input dtos.GetTaskInput) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, input)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskServiceMockRecorder) GetTask(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskService)(nil).GetTask), ctx, input)
}

// GetTaskSummaryByEmployee mocks base method.
func (m *MockTaskService) GetTaskSummaryByEmployee(ctx context.Context, input dtos.GetTaskSummaryByEmployeeInput) ([]dtos.EmployeeTaskSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskSummaryByEmployee", ctx, input)
	ret0, _ := ret[0].([]dtos.EmployeeTaskSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskSummaryByEmployee indicates an expected call of GetTaskSummaryByEmployee.
func (mr *MockTaskServiceMockRecorder) GetTaskSummaryByEmployee(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskSummaryByEmployee", reflect.TypeOf((*MockTaskService)(nil).GetTaskSummaryByEmployee), ctx, input)
}

// GetTasksWithFilter mocks base method.
func (m *MockTaskService) GetTasksWithFilter(ctx context.Context, input dtos.GetTasksWithFilterInput) ([]*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksWithFilter", ctx, input)
	ret0, _ := ret[0].([]*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksWithFilter indicates an expected call of GetTasksWithFilter.
func (mr *MockTaskServiceMockRecorder) GetTasksWithFilter(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksWithFilter", reflect.TypeOf((*MockTaskService)(nil).GetTasksWithFilter), ctx, input)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskService) UpdateTaskStatus(ctx context.Context, input dtos.UpdateTaskStatusInput) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, input)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskServiceMockRecorder) UpdateTaskStatus(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskService)(nil).UpdateTaskStatus), ctx, input)
}
